// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UAInnovate2026backend.Data;

#nullable disable

namespace UAInnovate2026backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260228204626_addModels")]
    partial class addModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UAInnovate2026backend.Models.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("UAInnovate2026backend.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HeroId")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.HasIndex("ResourceId");

                    b.HasIndex("SectorId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("UAInnovate2026backend.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("UAInnovate2026backend.Models.ResourceStockLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SectorResourceId")
                        .HasColumnType("int");

                    b.Property<bool>("SnapEvent")
                        .HasColumnType("bit");

                    b.Property<float>("StockLevel")
                        .HasColumnType("real");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<float>("Usage")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("SectorResourceId");

                    b.ToTable("ResourceStockLevels");
                });

            modelBuilder.Entity("UAInnovate2026backend.Models.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("UAInnovate2026backend.Models.SectorResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("SectorId");

                    b.ToTable("SectorResources");
                });

            modelBuilder.Entity("UAInnovate2026backend.Models.Report", b =>
                {
                    b.HasOne("UAInnovate2026backend.Models.Hero", "Hero")
                        .WithMany("Reports")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UAInnovate2026backend.Models.Resource", "Resource")
                        .WithMany("Reports")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UAInnovate2026backend.Models.Sector", "Sector")
                        .WithMany("Reports")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");

                    b.Navigation("Resource");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("UAInnovate2026backend.Models.ResourceStockLevel", b =>
                {
                    b.HasOne("UAInnovate2026backend.Models.SectorResource", "SectorResource")
                        .WithMany("ResourceStockLevels")
                        .HasForeignKey("SectorResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SectorResource");
                });

            modelBuilder.Entity("UAInnovate2026backend.Models.SectorResource", b =>
                {
                    b.HasOne("UAInnovate2026backend.Models.Resource", "Resource")
                        .WithMany("SectorResources")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UAInnovate2026backend.Models.Sector", "Sector")
                        .WithMany("SectorResources")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("UAInnovate2026backend.Models.Hero", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("UAInnovate2026backend.Models.Resource", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("SectorResources");
                });

            modelBuilder.Entity("UAInnovate2026backend.Models.Sector", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("SectorResources");
                });

            modelBuilder.Entity("UAInnovate2026backend.Models.SectorResource", b =>
                {
                    b.Navigation("ResourceStockLevels");
                });
#pragma warning restore 612, 618
        }
    }
}
